### ISSUE TITLE
大佬，我想贡献httprunner2.0.0版本的extentsreport

### ISSUE THREAD

**Issue by weirdohaibo** [httprunner/httprunner#575]
大佬，我想贡献httprunner2.0.0版本的extentsreport, 
项目地址：https://github.com/weirdohaibo/extentreportTemplates
我的邮箱： xuhaibo183@icloud.com

**Comment by stephenlee622** [comment]
> 大佬，我想贡献httprunner2.0.0版本的extentsreport,
> 项目地址：https://github.com/weirdohaibo/extentreportTemplates
> 我的邮箱： [xuhaibo183@icloud.com](mailto:xuhaibo183@icloud.com)

给你大大的拥抱

**Comment by 406722575** [comment]
使用模板时有如下报错，另外在pycharm中查看hmtl有不少红色提示重复ID等
Traceback (most recent call last):
  File "D:/HttpRunner/run.py", line 12, in <module>
    runner.run(r"D:\HttpRunner\projects\fscity\tests")
  File "D:\HttpRunner\httprunner\api.py", line 264, in run
    return self.run_path(path_or_tests, dot_env_path, mapping)
  File "D:\HttpRunner\httprunner\api.py", line 252, in run_path
    return self.run_tests(tests_mapping)
  File "D:\HttpRunner\httprunner\api.py", line 198, in run_tests
    self.report_dir
  File "D:\HttpRunner\httprunner\report.py", line 310, in render_html_report
    ).render(summary)
  File "D:\python3.6\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python3.6\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 550, in top-level template code
  File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'stat'

**Comment by weirdohaibo** [comment]
你的httprunner版本是多少？

**Comment by 406722575** [comment]
最新的2.1.2




------------------ 原始邮件 ------------------
发件人: "weirdo"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 上午8:35
收件人: "HttpRunner/HttpRunner"<HttpRunner@noreply.github.com>;
抄送: "Nic"<406722575@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575)




 你的httprunner版本是多少？

**Comment by weirdohaibo** [comment]
好的，应该是版本不兼容的问题。。我抽空看看吧。 id号重复不影响使用，我也不太好改，涉及的extentreport源码太多

**Comment by weirdohaibo** [comment]
> 最新的2.1.2
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "weirdo"<notifications@github.com>; 发送时间: 2019年5月21日(星期二) 上午8:35 收件人: "HttpRunner/HttpRunner"<HttpRunner@noreply.github.com>; 抄送: "Nic"<406722575@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 你的httprunner版本是多少？ 在 2019年5月20日，下午2:25，iphonex <notifications@github.com> 写道： 使用模板时有如下报错，另外在pycharm中查看hmtl有不少红色提示重复ID等 Traceback (most recent call last): File "D:/HttpRunner/run.py", line 12, in runner.run(r"D:\HttpRunner\projects\fscity\tests") File "D:\HttpRunner\httprunner\api.py", line 264, in run return self.run_path(path_or_tests, dot_env_path, mapping) File "D:\HttpRunner\httprunner\api.py", line 252, in run_path return self.run_tests(tests_mapping) File "D:\HttpRunner\httprunner\api.py", line 198, in run_tests self.report_dir File "D:\HttpRunner\httprunner\report.py", line 310, in render_html_report ).render(summary) File "D:\python3.6\lib\site-packages\jinja2\asyncsupport.py", line 76, in render return original_render(self, *args, **kwargs) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb) File "D:\python3.6\lib\site-packages\jinja2_compat.py", line 37, in reraise raise value.with_traceback(tb) File "", line 550, in top-level template code File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 430, in getattr return getattr(obj, attribute) jinja2.exceptions.UndefinedError: 'list object' has no attribute 'stat' — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

你的运行代码是什么？方便我看下吗？

**Comment by 406722575** [comment]
我重新运行了，又没问题了，




------------------ 原始邮件 ------------------
发件人: "weirdo"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 上午10:13
收件人: "HttpRunner/HttpRunner"<HttpRunner@noreply.github.com>;
抄送: "Nic"<406722575@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575)



 
最新的2.1.2
 …
 ------------------ 原始邮件 ------------------ 发件人: "weirdo"notifications@github.com; 发送时间: 2019年5月21日(星期二) 上午8:35 收件人: "HttpRunner/HttpRunner"HttpRunner@noreply.github.com; 抄送: "Nic"406722575@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 你的httprunner版本是多少？ 在 2019年5月20日，下午2:25，iphonex notifications@github.com 写道： 使用模板时有如下报错，另外在pycharm中查看hmtl有不少红色提示重复ID等 Traceback (most recent call last): File "D:/HttpRunner/run.py", line 12, in runner.run(r"D:\HttpRunner\projects\fscity\tests") File "D:\HttpRunner\httprunner\api.py", line 264, in run return self.run_path(path_or_tests, dot_env_path, mapping) File "D:\HttpRunner\httprunner\api.py", line 252, in run_path return self.run_tests(tests_mapping) File "D:\HttpRunner\httprunner\api.py", line 198, in run_tests self.report_dir File "D:\HttpRunner\httprunner\report.py", line 310, in render_html_report ).render(summary) File "D:\python3.6\lib\site-packages\jinja2\asyncsupport.py", line 76, in render return original_render(self, *args, **kwargs) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb) File "D:\python3.6\lib\site-packages\jinja2_compat.py", line 37, in reraise raise value.with_traceback(tb) File "", line 550, in top-level template code File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 430, in getattr return getattr(obj, attribute) jinja2.exceptions.UndefinedError: 'list object' has no attribute 'stat' — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
你的运行代码是什么？方便我看下吗？

**Comment by weirdohaibo** [comment]
> 我重新运行了，又没问题了，
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "weirdo"<notifications@github.com>; 发送时间: 2019年5月21日(星期二) 上午10:13 收件人: "HttpRunner/HttpRunner"<HttpRunner@noreply.github.com>; 抄送: "Nic"<406722575@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 最新的2.1.2 … ------------------ 原始邮件 ------------------ 发件人: "weirdo"notifications@github.com; 发送时间: 2019年5月21日(星期二) 上午8:35 收件人: "HttpRunner/HttpRunner"HttpRunner@noreply.github.com; 抄送: "Nic"406722575@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 你的httprunner版本是多少？ 在 2019年5月20日，下午2:25，iphonex notifications@github.com 写道： 使用模板时有如下报错，另外在pycharm中查看hmtl有不少红色提示重复ID等 Traceback (most recent call last): File "D:/HttpRunner/run.py", line 12, in runner.run(r"D:\HttpRunner\projects\fscity\tests") File "D:\HttpRunner\httprunner\api.py", line 264, in run return self.run_path(path_or_tests, dot_env_path, mapping) File "D:\HttpRunner\httprunner\api.py", line 252, in run_path return self.run_tests(tests_mapping) File "D:\HttpRunner\httprunner\api.py", line 198, in run_tests self.report_dir File "D:\HttpRunner\httprunner\report.py", line 310, in render_html_report ).render(summary) File "D:\python3.6\lib\site-packages\jinja2\asyncsupport.py", line 76, in render return original_render(self, *args, **kwargs) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb) File "D:\python3.6\lib\site-packages\jinja2_compat.py", line 37, in reraise raise value.with_traceback(tb) File "", line 550, in top-level template code File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 430, in getattr return getattr(obj, attribute) jinja2.exceptions.UndefinedError: 'list object' has no attribute 'stat' — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 你的运行代码是什么？方便我看下吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

好的。。。因为我刚在我这里运行也没问题

**Comment by 406722575** [comment]
嗯嗯，高大上，点赞

**Comment by 406722575** [comment]
老铁，发现了一个bug
在testcase中引用登录的用例，会报错，但是我用旧的报告模板运行是正常的





------------------ 原始邮件 ------------------
发件人: "weirdo"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 上午10:16
收件人: "HttpRunner/HttpRunner"<HttpRunner@noreply.github.com>;
抄送: "Nic"<406722575@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575)



 
我重新运行了，又没问题了，
 …
 ------------------ 原始邮件 ------------------ 发件人: "weirdo"notifications@github.com; 发送时间: 2019年5月21日(星期二) 上午10:13 收件人: "HttpRunner/HttpRunner"HttpRunner@noreply.github.com; 抄送: "Nic"406722575@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 最新的2.1.2 … ------------------ 原始邮件 ------------------ 发件人: "weirdo"notifications@github.com; 发送时间: 2019年5月21日(星期二) 上午8:35 收件人: "HttpRunner/HttpRunner"HttpRunner@noreply.github.com; 抄送: "Nic"406722575@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 你的httprunner版本是多少？ 在 2019年5月20日，下午2:25，iphonex notifications@github.com 写道： 使用模板时有如下报错，另外在pycharm中查看hmtl有不少红色提示重复ID等 Traceback (most recent call last): File "D:/HttpRunner/run.py", line 12, in runner.run(r"D:\HttpRunner\projects\fscity\tests") File "D:\HttpRunner\httprunner\api.py", line 264, in run return self.run_path(path_or_tests, dot_env_path, mapping) File "D:\HttpRunner\httprunner\api.py", line 252, in run_path return self.run_tests(tests_mapping) File "D:\HttpRunner\httprunner\api.py", line 198, in run_tests self.report_dir File "D:\HttpRunner\httprunner\report.py", line 310, in render_html_report ).render(summary) File "D:\python3.6\lib\site-packages\jinja2\asyncsupport.py", line 76, in render return original_render(self, *args, **kwargs) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb) File "D:\python3.6\lib\site-packages\jinja2_compat.py", line 37, in reraise raise value.with_traceback(tb) File "", line 550, in top-level template code File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 430, in getattr return getattr(obj, attribute) jinja2.exceptions.UndefinedError: 'list object' has no attribute 'stat' — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 你的运行代码是什么？方便我看下吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
好的。。。因为我刚在我这里运行也没问题

**Comment by weirdohaibo** [comment]
贴个报错截图呗。。。

**Comment by 406722575** [comment]
额，记得是有截图的，再补下


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: weirdo <notifications@github.com>
发送时间: 2019年5月28日 20:03
收件人: HttpRunner/HttpRunner <HttpRunner@noreply.github.com>
抄送: iphonex <406722575@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575)



贴个报错截图呗。。。

**Comment by 406722575** [comment]
附件


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: weirdo <notifications@github.com>
发送时间: 2019年5月28日 20:03
收件人: HttpRunner/HttpRunner <HttpRunner@noreply.github.com>
抄送: iphonex <406722575@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575)



贴个报错截图呗。。。

**Comment by weirdohaibo** [comment]
> 附件 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: weirdo <notifications@github.com> 发送时间: 2019年5月28日 20:03 收件人: HttpRunner/HttpRunner <HttpRunner@noreply.github.com> 抄送: iphonex <406722575@qq.com>, Comment <comment@noreply.github.com> 主题: 回复：[HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 贴个报错截图呗。。。 在 2019年5月28日，下午3:12，iphonex <notifications@github.com> 写道： 老铁，发现了一个bug 在testcase中引用登录的用例，会报错，但是我用旧的报告模板运行是正常的 ------------------ 原始邮件 ------------------ 发件人: "weirdo"<notifications@github.com>; 发送时间: 2019年5月21日(星期二) 上午10:16 收件人: "HttpRunner/HttpRunner"<HttpRunner@noreply.github.com>; 抄送: "Nic"<406722575@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 我重新运行了，又没问题了， … ------------------ 原始邮件 ------------------ 发件人: "weirdo"notifications@github.com; 发送时间: 2019年5月21日(星期二) 上午10:13 收件人: "HttpRunner/HttpRunner"HttpRunner@noreply.github.com; 抄送: "Nic"406722575@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 最新的2.1.2 … ------------------ 原始邮件 ------------------ 发件人: "weirdo"notifications@github.com; 发送时间: 2019年5月21日(星期二) 上午8:35 收件人: "HttpRunner/HttpRunner"HttpRunner@noreply.github.com; 抄送: "Nic"406722575@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575) 你的httprunner版本是多少？ 在 2019年5月20日，下午2:25，iphonex notifications@github.com 写道： 使用模板时有如下报错，另外在pycharm中查看hmtl有不少红色提示重复ID等 Traceback (most recent call last): File "D:/HttpRunner/run.py", line 12, in runner.run(r"D:\HttpRunner\projects\fscity\tests") File "D:\HttpRunner\httprunner\api.py", line 264, in run return self.run_path(path_or_tests, dot_env_path, mapping) File "D:\HttpRunner\httprunner\api.py", line 252, in run_path return self.run_tests(tests_mapping) File "D:\HttpRunner\httprunner\api.py", line 198, in run_tests self.report_dir File "D:\HttpRunner\httprunner\report.py", line 310, in render_html_report ).render(summary) File "D:\python3.6\lib\site-packages\jinja2\asyncsupport.py", line 76, in render return original_render(self, *args, **kwargs) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True) File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb) File "D:\python3.6\lib\site-packages\jinja2_compat.py", line 37, in reraise raise value.with_traceback(tb) File "", line 550, in top-level template code File "D:\python3.6\lib\site-packages\jinja2\environment.py", line 430, in getattr return getattr(obj, attribute) jinja2.exceptions.UndefinedError: 'list object' has no attribute 'stat' — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 你的运行代码是什么？方便我看下吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 好的。。。因为我刚在我这里运行也没问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

看不见你的报错截图啊...直接发堆栈信息吧

**Comment by 406722575** [comment]
![image](https://user-images.githubusercontent.com/39303693/58523738-2be7e100-81f8-11e9-83d6-64f028865d74.png)

**Comment by weirdohaibo** [comment]
我这里没有复现,你那里应该不是我仓库的最新代码,你去我仓库下载最新的再试试看

**Comment by weirdohaibo** [comment]
@406722575 我这里没有复现,你那里应该不是我仓库的最新代码,你去我仓库下载最新的再试试看

**Comment by 406722575** [comment]
下载了最新的也是一样
![image](https://user-images.githubusercontent.com/39303693/58525489-7ff5c400-81fe-11e9-9da9-08eb231eb333.png)

**Comment by weirdohaibo** [comment]
@406722575 修复好了,去我仓库下载吧

**Comment by 406722575** [comment]
厉害，没问题了




------------------ 原始邮件 ------------------
发件人: "weirdo"<notifications@github.com>;
发送时间: 2019年5月29日(星期三) 下午3:56
收件人: "HttpRunner/HttpRunner"<HttpRunner@noreply.github.com>;
抄送: "Nic"<406722575@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575)




@406722575 修复好了,去我仓库下载吧

**Comment by 406722575** [comment]
![image](https://user-images.githubusercontent.com/39303693/58541338-da5a4900-822d-11e9-8726-f4962f80a10d.png)

还有一个小bug，分类下的Timestamp没有显示

**Comment by weirdohaibo** [comment]
嗯，疏忽了，一个字段名字写错了。上传了

**Comment by weirdohaibo** [comment]
@406722575 现在text内容显示不全吗？还是被缩起来了？还是被截断了？

**Comment by 406722575** [comment]
固定了长度后面都是以省略号代替（像这样... OMITTED 44484 CHARACTORS ...），原模板也是这样，显示全了方便调试




------------------ 原始邮件 ------------------
发件人: "weirdo"<notifications@github.com>;
发送时间: 2019年5月29日(星期三) 下午4:51
收件人: "HttpRunner/HttpRunner"<HttpRunner@noreply.github.com>;
抄送: "Nic"<406722575@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [HttpRunner/HttpRunner] 大佬，我想贡献httprunner2.0.0版本的extentsreport (#575)




@406722575 现在text内容显示不全吗？还是被缩起来了？还是被截断了？

**Comment by 406722575** [comment]
> @406722575 现在text内容显示不全吗？还是被缩起来了？还是被截断了？

这个问题我找到源码了，修改了长度没问题
![image](https://user-images.githubusercontent.com/39303693/58674837-3d5df400-8384-11e9-85f4-cb7665844d2f.png)

**Comment by weirdohaibo** [comment]
好的

**Comment by erolce** [comment]
请问第三个tab是什么？为什么我使用后没有那个tab
![image](https://user-images.githubusercontent.com/21331818/58934333-ba320900-879c-11e9-92d7-8933928a9ee1.png)

![image](https://user-images.githubusercontent.com/21331818/58934351-c8802500-879c-11e9-88cb-bba08ec22ce4.png)

**Comment by weirdohaibo** [comment]
那个没什么用我删掉了。。。这张图没有更新，我抽时间换个图吧


许海波

**Comment by footmanqq** [comment]
为何我看xxx.summary.json里，只有time.start_at（修改模版都用这个字段，显示时间戳），没有time.start_datetime（原默认模版是用该字段，能显示给人看的日期时间）。

**Comment by weirdohaibo** [comment]
并没有见过你说的那个字段。。。你httprunner版本是多少


许海波

**Comment by debugtalk** [comment]
@weirdohaibo 欢迎提交 PR

**Comment by weirdohaibo** [comment]
> @weirdohaibo 欢迎提交 PR

好像需要大佬你邀请我进这个组织，我才能把仓库贡献进来。。

**Comment by debugtalk** [comment]
> > @weirdohaibo 欢迎提交 PR
> 
> 好像需要大佬你邀请我进这个组织，我才能把仓库贡献进来。。

https://help.github.com/en/articles/about-pull-requests

**Comment by weirdohaibo** [comment]
我最近也发现时间有点不对，这个时间是直接取的httprunner返回的


许海波
